<a href="https://colab.research.google.com/github/hamzayawa/pytorch_tut/blob/main/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install opendatasets --quiet
import opendatasets as od
od.download("https://www.kaggle.com/datasets/mssmartypants/rice-type-classification")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: yawaquest
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/mssmartypants/rice-type-classification


100%|██████████| 888k/888k [00:01<00:00, 792kB/s]

In [ ]:
import torch
import torch.nn as nn
from torch.optim import Adam
from torch.utils.data import Dataset, DataLoader
from torchsummary import summary
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [ ]:
df = pd.read_csv("/content/rice-type-classification/riceClassification.csv")

In [ ]:
df.head()

,id,Area,MajorAxisLength,MinorAxisLength,Eccentricity,ConvexArea,EquivDiameter,Extent,Perimeter,Roundness,AspectRation,Class
0,1,4537,92.229316,64.012769,0.719916,4677,76.004525,0.657536,273.085,0.764510,1.440796,1
1,2,2872,74.691881,51.400454,0.725553,3015,60.471018,0.713009,208.317,0.831658,1.453137,1
2,3,3048,76.293164,52.043491,0.731211,3132,62.296341,0.759153,210.012,0.868434,1.465950,1
3,4,3073,77.033628,51.928487,0.738639,3157,62.551300,0.783529,210.657,0.870203,1.483456,1
4,5,3693,85.124785,56.374021,0.749282,3802,68.571668,0.769375,230.332,0.874743,1.510000,1


In [ ]:
df.shape

(18185, 12)

In [ ]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
np1 = np.random.randn(3,4)
np1

array([[ 1.23848249, -0.97398161, -0.53598427, -0.39888817],
       [ 0.54806878,  0.16211818, -1.0588018 ,  0.97830053],
       [ 0.92163965,  0.78839795, -0.54579021, -0.41402811]])

In [ ]:
tens = torch.rand(3,4)
tens

tensor([[0.3187, 0.8917, 0.5518, 0.5975],
        [0.6254, 0.5519, 0.1471, 0.2627],
        [0.3739, 0.0678, 0.8117, 0.7657]])

In [ ]:
tensor_3d = torch.ones(3,3,4)
tensor_3d

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[ 1.2385, -0.9740, -0.5360, -0.3989],
        [ 0.5481,  0.1621, -1.0588,  0.9783],
        [ 0.9216,  0.7884, -0.5458, -0.4140]], dtype=torch.float64)